server:
    port: 8081
    servlet:
        context-path: /PenguinStats
spring:
    data:
        mongodb:
            uri: mongodb://username:password@localhost:27017/penguin_stats
    cache:
        jcache:
            config: classpath:ehcache.xml
