server:
    port: 8081
    servlet:
        context-path: /PenguinStats
spring:
    data:
        mongodb:
            uri: mongodb://username:password@localhost:27017/penguin_stats
    cache:
        jcache:
            config: classpath:ehcache.xml
justauth:
  enabled: true
  type:
    QQ:
      client-id: <client-id>
      client-secret: <client-secret>
      redirect-uri: https://penguin-stats.cn/PenguinStats/api/v2/users/oauth/qq/callback
      union-id: false
    Google:
      client-id: <client-id>
      client-secret: <client-secret>
      redirect-uri: https://penguin-stats.cn/PenguinStats/api/v2/users/oauth/google/callback
  cache:
    type: default